moji/banking/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

app_name = 'banking'

urlpatterns = [
    url(r'^step1/$', views.number1, name='step1'),
    url(r'^step2/$', views.number2, name='step2'),
    url(r'^step3/$', views.number3, name='step3'),
    url(r'^step/$', views.new, name='step'),
]

moji/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index ,name='home'),
    url(r'^bug/$', views.emailReport.as_view(), name='bug'),
    url(r'^search/$', views.SearchUser, name='search')

]

moji/moji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^content/', include('content.urls')),
    url(r'^home/', include('home.urls')),
    #url(r'^product/', include('product.urls')),
    url(r'^banking/', include('banking.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moji/banking/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid




class Wallet(models.Model):
    user = models.OneToOneField(User)
    amount = models.PositiveIntegerField(default=0)
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)#this will be the primary key


'''
class TransactionHistory(models.Model):
    user = models.ForeignKey(User)
    transction =
    date =
    types = models.CharField(max_length=10, choices=Types)
'''

moji/home/models.py
from django.db import models

# Create your models here.

moji/home/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

class Reporter(forms.Form):
    Report = (('bug', 'bug'), ('violation', 'violation'), ('support', 'support'), 'advice', 'advice')

    email = forms.EmailField(required=True)
    message = forms.CharField(max_length=255, required=True)
    #add a choice to subject
    sub = ''

    #message = forms.ChoiceField(choices=Report)
    Subject = forms.CharField(max_length=55, required=True)

    def send_email(self):
        #subject = 'bug'
        subject = self.cleaned_data['Subject']
        message = self.cleaned_data['message']
        from_email = self.cleaned_data['email']
        recipient_list = [settings.EMAIL_HOST,]
        return send_mail(subject, message, from_email, recipient_list, fail_silently=False,)

moji/banking/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
import requests
import json
from django.conf import settings
from content.models import Content

def number1(request):
    #in templates after successful creation, change button to edit payout info
    return render(request, 'banking/bank.html')

def number2(request):
    Acode = request.GET.get('code')
    if Acode:
        data = [
        ('client_secret', 'sk_test_KfXaKQvXftN0sR3GfoDLQhfs'),
        ('code', Acode),
        ('grant_type', 'authorization_code'),
        ]

    response = requests.post('https://connect.stripe.com/oauth/token', data=data)
    if response.status_code == 200:
        a = json.loads(response.text)
        #ConnectStripeAccount.objects.create(stripe_id=(a['stripe_user_id']), ...)
    else:
        #error response
        None
    #return redirect(reverse('account:ProfileView', kwargs={'user':request.user.get_absolute_url))

def number3(request):
    source = request.POST.get('stripeToken')
    return render(request, 'banking/token.html', {'source':source})


def new(request):
    item = Content.objects.filter()[2]
    user = request.user
    return render(request, 'banking/n.html', {'item':item, 'user':user})

moji/home/views.py
from django.shortcuts import render, redirect, Http404
from content.models import Content, Comment, Like
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.conf import settings
from .forms import Reporter
from django.db.models import Q

def index(request):
    followers = request.user.profile.following.all()
    #followers.append(user)
    queryset_list = Content.objects.filter(user__in=followers).order_by('-date')
    return render(request, 'banking/n.html', {'queryset_list':queryset_list})


def SearchUser(request):
    query = request.GET.get('q')
    if query:
        queryset_list = Profile.objects.filter(
        Q(user__username__icontains=query) |
        Q(location__icontains=query) |
        Q(user__first_name__icontains=query) |
        Q(user__last_name__icontains=query)
        ).distinct()
        return render(request, 'home/SearchUser.html', {'queryset_list':queryset_list})
    else:
        return None

def discoverView(request):
    page = 'Spotlight'
    users = User.objects.filter('?')[:24]
    return render(request, 'home/discover.html', {'users':users, 'page':page})

def discoverGenre(request, genre):
    try:
        users = Profile.objects.filter(genre_exact=genre)[:24]
    except Profile.DoesNotExist:
        raise http404('cant find any users under this genre')
    page = genre
    return render(request, 'home/genreUsers.html', {'users':users, 'page':page})

class emailReport(FormView):
    template_name = 'home/contact.html'
    form_class = Reporter
    success_url = '/home/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(emailReport, self).form_valid(form)


'''
class BugReport(emailReport):
    we dont need their email
    user makes the message, subject is always bug
    pass

class ViolationReport(emailReport):
    we dont need their email
    should just be choice:
    ex.
    illegal content
    slander
    bullying
    offensive
    missed advertised
    aggresive or endangering of human/animal
    copyright
    and then grabs a screenshot of the violation
    pass

class ContactReport(emailReport):
    user makes subject and message
    we need their email
    this is for potential users or celebs
    pass

class SupportReport(emailReport):
    user makes subject and message, and the users account
    we need their email
    this is for paid users, about their account or using the service
    pass
'''

moji/banking/templates/banking/bank.html
<h2>step 1</h2>
<a href=https://connect.stripe.com/express/oauth/authorize?redirect_uri={% url 'banking:step2' %}&client_id=ca_Cy94GsAPP0p1bh123Wu3eyXPudMGpZjg
&state=verified>connect</a>

<form action="{% url 'banking:step3' %}" method="POST">{% csrf_token %}
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_JJ1kyJo7vcwNwhRksCw6xsHC"
    data-amount="999"
    data-name="Stripe.com"
    data-description="Widget"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-zip-code="true"
    data-shipping-address='true'
    data-billing-address='true'>
  </script>
</form>

<h2>{{source}}</h2>

moji/banking/templates/banking/home.html
{% extends 'banking\new.html' %}

{% block body %}
<div class="row bootstrap snippet">
    <div class="col-md-7 col-xs-12 col-md-offset-3">
      <div class="panel" id="daily-feed">
        <div class="panel-heading">
          <h3 class="panel-title">Daily feed
            <span class="pull-right label label-round label-warning">10 Messages</span>
          </h3>
        </div>
        <div class="panel-body">
          <ul class="list-group list-group-dividered list-group-full">
            <li class="list-group-item">
              <div class="media">
                <div class="media-left">
                  <a class="avatar avatar-online" href="javascript:void(0)">
                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt=""><i></i></a>
                </div>
                <div class="media-body">
                  <h4 class="media-heading">
                    <small class="pull-right">5m ago</small>
                    <a class="name">Edward Fletcher</a> posted a new blog.
                  </h4>
                  <small>Today 5:50 pm - 12.04.2015</small>
                </div>
              </div>
            </li>
            <li class="list-group-item">
              <div class="media">
                <div class="media-left">
                  <a class="avatar avatar-off" href="javascript:void(0)">
                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt=""><i></i></a>
                </div>
                <div class="media-body">
                  <h4 class="media-heading">
                    <small class="pull-right">2h ago</small>
                    <a class="name">Justin Martin</a> posted message on
                    <a class="name">Crystal Bates</a> site.
                  </h4>
                  <small>Today 2:55 pm - 12.04.2015</small>
                  <div class="actions margin-top-10">
                    <button type="button" class="btn btn-danger btn-xs waves-effect waves-light"><i class="icon md-thumb-up" aria-hidden="true"></i>Like</button>
                    <button type="button" class="btn btn-danger btn-xs waves-effect waves-light"><i class="icon md-favorite" aria-hidden="true"></i>Love</button>
                  </div>
                </div>
              </div>
            </li>
            <li class="list-group-item">
              <div class="media">
                <div class="media-left">
                  <a class="avatar avatar-away" href="javascript:void(0)">
                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt=""><i></i></a>
                </div>
                <div class="media-body">
                  <h4 class="media-heading">
                    <small class="pull-right">6h ago</small>
                    <a class="name">Terrance Arnold</a> posted message on
                    <a class="name">Nathan Watts</a> site.
                  </h4>
                  <small>Today 12:00 am - 12.04.2015</small>
                  <div class="content well">
                    Aspernatur ad aspernari sapienter constringendos conspiratione locatus. Ii maiores
                    aequo tollit, profecta iucundo pueros assentior velit circumcisaque
                    error fastidium nostros. Utuntur deserunt solvantur.
                  </div>
                </div>
              </div>
            </li>
            <li class="list-group-item">
              <div class="media">
                <div class="media-left">
                  <a class="avatar avatar-busy" href="javascript:void(0)">
                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt=""><i></i></a>
                </div>
                <div class="media-body">
                  <h4 class="media-heading">
                    <small class="pull-right">20h ago</small>
                    <a class="name">Heather Harper</a> started following
                    <a class="name">Terrance Arnold</a>.
                  </h4>
                  <small>Yesterday 9:00 pm - 11.04.2015</small>
                </div>
              </div>
            </li>
          </ul>
          <button type="button" class="btn btn-block btn-primary waves-effect waves-light"><i class="icon md-chevron-down margin-right-5" aria-hidden="true"></i>Show
            More</button>
        </div>
      </div>
    </div>
</div>
{% endblock %}

moji/banking/templates/banking/n.html
{% extends 'home/new.html' %}

{% block f %}
{% load staticfiles %}


<div class="card">
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://i.imgur.com/VxmXgqT.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>

{% endblock %}

moji/banking/templates/banking/n1.html
{% extends 'home/new.html' %}

{% block f %}

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalContactForm">
  Launch
</button>


<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Write to us</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
                <div class="md-form mb-5">
                    <i class="fa fa-user prefix grey-text"></i>
                    <input type="text" id="form34" class="form-control validate">
                    <label data-error="wrong" data-success="right" for="form34">Your name</label>
                </div>

                <div class="md-form mb-5">
                    <i class="fa fa-envelope prefix grey-text"></i>
                    <input type="email" id="form29" class="form-control validate">
                    <label data-error="wrong" data-success="right" for="form29">Your email</label>
                </div>

                <div class="md-form mb-5">
                    <i class="fa fa-tag prefix grey-text"></i>
                    <input type="text" id="form32" class="form-control validate">
                    <label data-error="wrong" data-success="right" for="form32">Subject</label>
                </div>

                <div class="md-form">
                    <i class="fa fa-pencil prefix grey-text"></i>
                    <textarea type="text" id="form8" class="md-textarea form-control" rows="4"></textarea>
                    <label data-error="wrong" data-success="right" for="form8">Your message</label>
                </div>

            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button class="btn btn-unique">Send <i class="fa fa-paper-plane-o ml-1"></i></button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

moji/banking/templates/banking/n2.html
{% extends 'home/new.html' %}

{% block f %}

<style>
body {
background-image: url("../images/.jpg");
background-color:white;;
background-attachment:scroll;
background-repeat:no-repeat;
background-position:center;
background-size:cover;
height:2000px;
}
/*----------------Containers--------------------*/

#top-container-fluid-nav
{
background-image: url("../images/.jpg");
background-color:inherit;
background-attachment:scroll;
background-repeat:no-repeat;
background-position:center;
background-size:cover	;
}

#body-container-fluid
{
background-image: url("../images/.jpg");
background-color:inherit;
background-attachment:scroll;
background-repeat:no-repeat;
background-position:center;
background-size:cover;
margin-top:50px;
}

#footer-container-fluid
{
background-image: url("../images/.jpg");
background-color:inherit;
background-attachment:scroll;
background-repeat:no-repeat;
background-position:center;
background-size:cover;
padding-bottom:25px;
padding-top:25px;
}

.card
{
padding:10px;
border:0px solid white;
box-shadow:0px 7px 16px 0px rgba(0, 0, 0, 0.09);
}
.card-title
{
color:;
font-size:16px;
text-align:center;
}
.card-text
{
color:#84919B;
font-size:12px;
text-align:center;

}

#courses
{
text-align:center;
}

/**********************
		courses
**********************/
.list-inline-item
{
font-size:13px;
color:#84919B;
 }
/**********************
		courses
**********************/


.address .w3-ul li
 {
	border:0px solid white;
	line-height:1px;
}



/**********************
		abilities
**********************/
span
{
font-size:10px;
float:right;
background-color:#F4F7F9;
border-radius:10px;
padding:3px 8px;
color:#84919B;
}
.lower-case
{
color:#84919B;
font-size:12px;
text-align:center;
}

/**********************
		abilities
**********************/




/**********************
		ratings
**********************/

.ratings .fa
{
color:indigo;
font-size:25px;
}
.ratings .fa:hover
{
color:yellow;
}
.ratings .list-inline
{
text-align:center;
}

/**********************
		ratings
**********************/





/**********************
		socials
**********************/
.socials {
text-align:center;
}

/**********************
		socials
**********************/




 /**********************
		footer
**********************/
.learn {font-size:12px;color:gray;}
.learn a:hover {text-decoration:none;}
/**********************
		footer
**********************/

 </style>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!---************* arrangement by john niro yumang b4.0 alpha project graduation ******************* -->

<!DOCTYPE html>
<html lang="en">

	<title>index</title>

		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!------------start head  scripts and link src------------>
	<head>


		<script src="js/jq.js"></script>
		<!---- for moving objects make this first always after boootstrap.css ----->

		<link rel="stylesheet" href="css/bootstrap.css">
		<!---- Bootstrap.min link local project skeleton ----->

		<link rel="stylesheet" href="css/w3.css">
		<!--- This is the local w3css extended --->

		<link rel="stylesheet" href="css/animate.css">

		<link rel="stylesheet" href="css/style.css">
		<!---- my own link local for customizing ----->

		<script src="js/bootstrap.min.js"></script>
		<!---- Bootstrap js link local for well and modal + panels ----->

		<link rel="icon" href="images/a.png" type="images/water.png" />
		<!---- Icon link local ----->

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
		<!-------    font awesome online plug --------------->
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


	</head>
	<!-------------end head scripts and link src ------------->







	<!------------start content ------------>
	<body>
		<div class="wrapper">
			<div class="container-fluid" id="top-container-fluid-nav">
				<div class="container">
					<!---- for nav container ----->
				</div>
			</div>


			<div class="container-fluid" id="body-container-fluid">
				<div class="container">
					<!---- for body container ---->
					<div class="row">
						 <!-------mother container middle class------------------->
						<div class="col-lg-4">
						<div class="card" style="width:100%">
							<img class="card-img-top" src="https://lh3.googleusercontent.com/a8_ujXr3VWHstGkxgJL1TkqfrytP4r_52QhcvqRQVaQPRQ9DHdQ6seI99qc4jLjC0WDM=h900" alt="Card image"  style="width:100%">
							<div class="card-body">
							  <h4 class="card-title">John Niro Yumang</h4>
							  	<ul class="list-inline" id="courses">
									<li class="list-inline-item">
										<i class="fa fa-folder-open-o"></i> Model
									</li>

								</ul>
								 <p class="card-text">I am a professional student designer i love my work so hire me !!</p>

								<div class="address">
								<ul class="w3-ul w3-small">
									<li> <i class="fa fa-calendar-o" aria-hidden="true"></i>  #403 3rd Block, Pampanga, Phillippines </li>
									<li><i class="fa fa-calendar-o" aria-hidden="true"></i> University of the Phillippines </li>
									<li><i class="fa fa-calendar-o" aria-hidden="true"></i> Region: Cali </li>
									<li><i class="fa fa-calendar-o" aria-hidden="true"></i> Join October 23 1990 </li>
								</ul>
								</address>

							 <p><button class="w3-button w3-block w3-indigo"   data-toggle="tooltip" data-placement="top" title="Free to message and hire us"> <i class="fa fa-comment-o fa-lg"></i> Cancel Subscription </button></p>
							</div>

								<ul class="w3-ul w3-small">
									<li><a href="" > Posts </a> <span>93</span></li>
									<li><a href="">Likes </a><span>12</span></li>
									<li><a href="">Comments </a><span>12</span></li>
								</ul>

							<hr>

							<div class="socials">
								<p class="lower-case ">  Follow us</p>
							<ul class="list-inline">
								<button class="w3-button w3-blue"><i class="fa fa-facebook"></i></button>
								<button class="w3-button w3-yellow"><i class="fa fa-twitter"></i></button>
                <button class="w3-button w3-purple"><i class="fa fa-instagram"></i></button>
								<button class="w3-button w3-green"><i class="fa fa-link"></i></button>
								<button class="w3-button w3-green"><i class="fa fa-link"></i></button>
 							</ul>
 							</div>

							<hr>
							<p class="lower-case ">  Fanmojis Username</p>

							<p class="text-center">Content by @Jhean_Yhu</p>

						</div>

						</div>












					</div>
				</div>
			</div>



			<div class="container-fluid" id="footer-container-fluid">
				<div class="container">
					<!---- for footer container ---->
 				</div>
			</div>



		</div>
 	</body>
	<!-------------end content-------------->

	<!------------sub footer code ------------>
	<footer>
	</footer>

	<!------------in-line script purpose ------------>
	<script>
	$('.carousel').carousel({
    interval: 2000
    })
	</script>




{% endblock %}

moji/banking/templates/banking/new.html
<!doctype html>
sucess
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load staticfiles %}

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>

    .footer {
        position: absolute;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #f5f5f5;
        height: 50px;
        line-height: 50px;
        color: black;
        text-align: center;
    }

    .dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
  }

  .dropdown {
    position: relative;
    display: inline-block;
  }

  .dropdown-menu {
    display: none;
    position: absolute;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }

  .dropdown-menu a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  .dropdown-menu a:hover {background-color: #ddd}

  .dropdown:hover .dropdown-menu {
    display: block;
  }

  .dropdown:hover .dropbtn {
    background-color: #3e8e41;
  }



    </style>
    <title>Hello, world!</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light py-3 ">
      <a class="navbar-brand font-weight-bold font-italic " href="#">Fanmojis</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link font-weight-bold" href="#">Discover</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle  font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Create
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item  font-weight-bold" href="#">Image</a>
              <a class="dropdown-item  font-weight-bold" href="#">Video</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item  font-weight-bold" href="#">Say Something</a>
            </div>
          </li>

        </ul>

        <div class="dropdown show">
        <a class="btn btn-primary dropdown-toggle mx-2 px-4 " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            John Adams <span class="badge badge-light ml-2">234</span>
            <span class="sr-only">followers</span>
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Billing</a>
          <a class="dropdown-item" href="#">Logout</a>
        </div>
      </div>


        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    {% else %}
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light py-3 ">
      <a class="navbar-brand font-weight-bold font-italic " href="#">Fanmojis</a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link font-weight-bold" href="#">How We Work</a>
          </li>
          <li class="nav-item">
            <a class="nav-link font-weight-bold" href="#">About Us</a>
          </li>
        </ul>


        <a class="nav-link font-weight-bold" href="#">Discover<i class="fab fa-wpexplorer ml-2"></i></a>

      </div>
    </nav>
    {% endif %}


<br>


<div class='container mt-4 pt-4'>
  {% block boody %}

  {% endblock %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



  <footer class="footer mt-3">

  <div class='row justify-content-between'>
    <div class="col-sm-3 col-md-auto col-lg-3">
      <a href="#" class="badge badge-pill badge-primary">Contact</a>
      <a href="#" class="badge badge-pill badge-primary">Twitter</a>
      <a href="#" class="badge badge-pill badge-primary">Instagram</a>
      <a href="#" class="badge badge-pill badge-primary">Terms</a>

    </div>

    <div class="col-md-auto  col-lg-3">
      <span class="text-muted font-weight-bold">© Hapi Cake Labs 2018-Present</span>
    </div>


  </div>
  </footer>

  </body>


</html>

moji/banking/templates/banking/token.html
<h2>token</h2>
<h2>{{ source }}</h2>